const STORAGE_PREFIX = "cartshare_room_";
let currentRoom = "";
let currentUser = "";

const $ = (id) => document.getElementById(id);

function roomKey(room) {
  return STORAGE_PREFIX + room.toUpperCase();
}

function createRoomCode() {
  return Math.random().toString(36).substring(2, 8).toUpperCase();
}

function getRoomData() {
  const raw = localStorage.getItem(roomKey(currentRoom));
  if (raw) return JSON.parse(raw);
  return { items: [], activities: [] };
}

function saveRoomData(data) {
  localStorage.setItem(roomKey(currentRoom), JSON.stringify(data));
  render();
}

function addActivity(data, text) {
  data.activities.unshift({
    text,
    user: currentUser,
    time: new Date().toLocaleString()
  });
  data.activities = data.activities.slice(0, 50);
}

function enterRoom(name, code) {
  currentUser = name.trim();
  currentRoom = (code.trim() || createRoomCode()).toUpperCase();

  let data = getRoomData();
  addActivity(data, `${currentUser} joined room ${currentRoom}.`);
  saveRoomData(data);

  $("welcomeSection").classList.add("d-none");
  $("appSection").classList.remove("d-none");
  $("roomBadge").classList.remove("d-none");
  $("roomBadge").textContent = "Room: " + currentRoom;
  $("roomCodeText").textContent = currentRoom;
  $("userText").textContent = currentUser;
  render();
}

$("joinForm").addEventListener("submit", (e) => {
  e.preventDefault();
  enterRoom($("userName").value, $("roomCode").value);
});

$("itemForm").addEventListener("submit", (e) => {
  e.preventDefault();
  if (!currentRoom) return;

  const name = $("itemName").value.trim();
  const qty = Number($("itemQty").value);
  const price = Number($("itemPrice").value);

  if (!name || qty < 1 || price < 0) return;

  const data = getRoomData();
  const item = {
    id: Date.now() + Math.random(),
    name,
    qty,
    price,
    addedBy: currentUser
  };

  data.items.push(item);
  addActivity(data, `${currentUser} added ${qty} × ${name}.`);
  saveRoomData(data);

  $("itemForm").reset();
  $("itemQty").value = 1;
  $("itemPrice").value = 0;
});

function removeItem(id) {
  const data = getRoomData();
  const item = data.items.find(x => x.id === id);
  if (!item) return;

  data.items = data.items.filter(x => x.id !== id);
  addActivity(data, `${currentUser} removed ${item.name}.`);
  saveRoomData(data);
}

function render() {
  if (!currentRoom) return;
  const data = getRoomData();

  const list = $("cartList");
  list.innerHTML = "";

  $("emptyCart").classList.toggle("d-none", data.items.length !== 0);
  $("itemCount").textContent = `${data.items.length} item${data.items.length === 1 ? "" : "s"}`;

  let total = 0;

  data.items.forEach(item => {
    const subtotal = item.qty * item.price;
    total += subtotal;

    const div = document.createElement("div");
    div.className = "cart-item";
    div.innerHTML = `
      <div class="d-flex justify-content-between gap-3">
        <div>
          <div class="fw-semibold">${escapeHtml(item.name)}</div>
          <div class="item-meta">${item.qty} × ₹${item.price.toFixed(2)} · Added by ${escapeHtml(item.addedBy)}</div>
        </div>
        <div class="text-end">
          <div class="fw-semibold">₹${subtotal.toFixed(2)}</div>
          <button class="btn btn-sm btn-outline-danger mt-1" onclick="removeItem(${item.id})">Remove</button>
        </div>
      </div>
    `;
    list.appendChild(div);
  });

  $("totalAmount").textContent = total.toFixed(2);

  $("activityLog").innerHTML = data.activities.length
    ? data.activities.map(a => `
      <div class="activity-entry">
        <div>${escapeHtml(a.text)}</div>
        <small class="text-muted">${escapeHtml(a.time)}</small>
      </div>
    `).join("")
    : '<div class="text-muted">No activity yet.</div>';
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

$("printBtn").addEventListener("click", () => {
  const data = getRoomData();
  const total = data.items.reduce((sum, x) => sum + x.qty * x.price, 0);

  const printWindow = window.open("", "_blank");
  printWindow.document.write(`
    <!doctype html>
    <html><head><title>CartShare Receipt</title>
    <style>
      body{font-family:Arial,sans-serif;max-width:760px;margin:30px auto;padding:20px}
      h1{margin-bottom:4px}.muted{color:#666}
      table{width:100%;border-collapse:collapse;margin-top:20px}
      th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}
      .right{text-align:right}.total{font-size:20px;font-weight:bold}
    </style></head>
    <body id="printArea">
      <h1>CartShare Receipt</h1>
      <div class="muted">Room: ${escapeHtml(currentRoom)}</div>
      <div class="muted">Generated by: ${escapeHtml(currentUser)}</div>
      <div class="muted">Date: ${new Date().toLocaleString()}</div>
      <table>
        <thead><tr><th>Item</th><th>Added By</th><th>Qty</th><th>Price</th><th class="right">Subtotal</th></tr></thead>
        <tbody>
          ${data.items.map(x => `
            <tr>
              <td>${escapeHtml(x.name)}</td>
              <td>${escapeHtml(x.addedBy)}</td>
              <td>${x.qty}</td>
              <td>₹${x.price.toFixed(2)}</td>
              <td class="right">₹${(x.qty*x.price).toFixed(2)}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
      <p class="total right">Total: ₹${total.toFixed(2)}</p>
      <p class="muted">Audit-ready summary generated by CartShare.</p>
      <script>window.onload=()=>window.print();<\/script>
    </body></html>
  `);
  printWindow.document.close();
});

$("leaveBtn").addEventListener("click", () => {
  if (currentRoom) {
    const data = getRoomData();
    addActivity(data, `${currentUser} left the room.`);
    saveRoomData(data);
  }
  currentRoom = "";
  currentUser = "";
  $("appSection").classList.add("d-none");
  $("welcomeSection").classList.remove("d-none");
  $("roomBadge").classList.add("d-none");
});

window.addEventListener("storage", (event) => {
  if (currentRoom && event.key === roomKey(currentRoom)) render();
});
