const STORAGE_PREFIX = "cartshare_room_";

let currentRoom = "";
let currentUser = "";

const $ = (id) => document.getElementById(id);

function roomKey(room) {
  return STORAGE_PREFIX + room.toUpperCase();
}

function createRoomCode() {
  return Math.random().toString(36).substring(2, 8).toUpperCase();
}

function getRoomData() {
  try {
    const raw = localStorage.getItem(roomKey(currentRoom));
    return raw ? JSON.parse(raw) : { items: [], activities: [] };
  } catch (error) {
    console.error("Storage error:", error);
    return { items: [], activities: [] };
  }
}

function saveRoomData(data) {
  localStorage.setItem(roomKey(currentRoom), JSON.stringify(data));
  render();
}

function addActivity(data, text) {
  data.activities.unshift({
    text: text,
    user: currentUser,
    time: new Date().toLocaleString()
  });

  data.activities = data.activities.slice(0, 50);
}

function enterRoom(name, code) {
  name = name.trim();
  code = code.trim();

  if (!name) {
    alert("Please enter your name.");
    return;
  }

  currentUser = name;
  currentRoom = (code || createRoomCode()).toUpperCase();

  let data = getRoomData();

  addActivity(
    data,
    `${currentUser} joined room ${currentRoom}.`
  );

  saveRoomData(data);

  $("welcomeSection").classList.add("d-none");
  $("appSection").classList.remove("d-none");
  $("roomBadge").classList.remove("d-none");

  $("roomBadge").textContent = "Room: " + currentRoom;
  $("roomCodeText").textContent = currentRoom;
  $("userText").textContent = currentUser;

  render();
}

document.addEventListener("DOMContentLoaded", function () {

  $("joinForm").addEventListener("submit", function (e) {
    e.preventDefault();

    enterRoom(
      $("userName").value,
      $("roomCode").value
    );
  });

  $("itemForm").addEventListener("submit", function (e) {
    e.preventDefault();

    if (!currentRoom) return;

    const name = $("itemName").value.trim();
    const qty = Number($("itemQty").value);
    const price = Number($("itemPrice").value);

    if (!name) {
      alert("Please enter item name.");
      return;
    }

    if (qty < 1) {
      alert("Quantity must be at least 1.");
      return;
    }

    if (price < 0) {
      alert("Price cannot be negative.");
      return;
    }

    const data = getRoomData();

    data.items.push({
      id: Date.now() + Math.random(),
      name: name,
      qty: qty,
      price: price,
      addedBy: currentUser
    });

    addActivity(
      data,
      `${currentUser} added ${qty} × ${name}.`
    );

    saveRoomData(data);

    $("itemForm").reset();
    $("itemQty").value = 1;
    $("itemPrice").value = 0;
  });

  $("printBtn").addEventListener("click", function () {

    if (!currentRoom) return;

    const data = getRoomData();

    const total = data.items.reduce(
      (sum, item) => sum + item.qty * item.price,
      0
    );

    const printWindow = window.open("", "_blank");

    if (!printWindow) {
      alert("Please allow pop-ups for the receipt.");
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>CartShare Receipt</title>

        <style>
          body {
            font-family: Arial, sans-serif;
            max-width: 760px;
            margin: 30px auto;
            padding: 20px;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }

          th, td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
            text-align: left;
          }

          .right {
            text-align: right;
          }

          .total {
            font-size: 20px;
            font-weight: bold;
          }
        </style>
      </head>

      <body>

        <h1>CartShare Receipt</h1>

        <p>Room: ${escapeHtml(currentRoom)}</p>
        <p>Generated by: ${escapeHtml(currentUser)}</p>
        <p>Date: ${new Date().toLocaleString()}</p>

        <table>

          <thead>
            <tr>
              <th>Item</th>
              <th>Added By</th>
              <th>Qty</th>
              <th>Price</th>
              <th>Subtotal</th>
            </tr>
          </thead>

          <tbody>

            ${data.items.map(item => `
              <tr>
                <td>${escapeHtml(item.name)}</td>
                <td>${escapeHtml(item.addedBy)}</td>
                <td>${item.qty}</td>
                <td>₹${item.price.toFixed(2)}</td>
                <td>₹${(item.qty * item.price).toFixed(2)}</td>
              </tr>
            `).join("")}

          </tbody>

        </table>

        <p class="total right">
          Total: ₹${total.toFixed(2)}
        </p>

        <script>
          window.onload = function() {
            window.print();
          };
        <\/script>

      </body>
      </html>
    `);

    printWindow.document.close();
  });

  $("leaveBtn").addEventListener("click", function () {

    if (currentRoom) {

      const data = getRoomData();

      addActivity(
        data,
        `${currentUser} left the room.`
      );

      saveRoomData(data);
    }

    currentRoom = "";
    currentUser = "";

    $("appSection").classList.add("d-none");
    $("welcomeSection").classList.remove("d-none");
    $("roomBadge").classList.add("d-none");
  });

});

function removeItem(id) {

  if (!currentRoom) return;

  const data = getRoomData();

  const item = data.items.find(
    item => item.id === id
  );

  if (!item) return;

  data.items = data.items.filter(
    item => item.id !== id
  );

  addActivity(
    data,
    `${currentUser} removed ${item.name}.`
  );

  saveRoomData(data);
}

function render() {

  if (!currentRoom) return;

  const data = getRoomData();

  const list = $("cartList");

  list.innerHTML = "";

  $("emptyCart").classList.toggle(
    "d-none",
    data.items.length !== 0
  );

  $("itemCount").textContent =
    `${data.items.length} item${data.items.length === 1 ? "" : "s"}`;

  let total = 0;

  data.items.forEach(item => {

    const subtotal = item.qty * item.price;

    total += subtotal;

    const div = document.createElement("div");

    div.className = "cart-item";

    div.innerHTML = `
      <div class="d-flex justify-content-between gap-3">

        <div>
          <div class="fw-semibold">
            ${escapeHtml(item.name)}
          </div>

          <div class="item-meta">
            ${item.qty} × ₹${item.price.toFixed(2)}
            · Added by ${escapeHtml(item.addedBy)}
          </div>
        </div>

        <div class="text-end">

          <div class="fw-semibold">
            ₹${subtotal.toFixed(2)}
          </div>

          <button
            class="btn btn-sm btn-outline-danger mt-1"
            onclick="removeItem(${item.id})">
            Remove
          </button>

        </div>

      </div>
    `;

    list.appendChild(div);
  });

  $("totalAmount").textContent =
    total.toFixed(2);

  $("activityLog").innerHTML =
    data.activities.length
      ? data.activities.map(activity => `
          <div class="activity-entry">
            <div>
              ${escapeHtml(activity.text)}
            </div>

            <small class="text-muted">
              ${escapeHtml(activity.time)}
            </small>
          </div>
        `).join("")
      : '<div class="text-muted">No activity yet.</div>';
}

function escapeHtml(value) {

  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

window.addEventListener("storage", function (event) {

  if (
    currentRoom &&
    event.key === roomKey(currentRoom)
  ) {
    render();
  }

});
